<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.3.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stingray.Domain\Stingray.Domain.csproj"/>
        <ProjectReference Include="..\Stingray.Storage.InMemory\Stingray.Storage.InMemory.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

</Project>
