<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stingray.Application\Stingray.Application.csproj"/>
        <ProjectReference Include="..\Stingray.Domain\Stingray.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.12.0"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.Extensions.Logging.Abstractions">
            <HintPath>..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.21\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
